/:
  Controller: MainController
  Action: "home"
  Security: false
  Role: "Guest"

/login:
  Controller: Security
  Action: "login"
  Security: false
  Role: "Guest"

/register:
  Controller: Security
  Action: "register"
  Security: false
  Role: "Guest"

/logout:
  Controller: Security
  Action: "logout"
  Security: true
  Role: "Guest"

/dashboard:
  Controller: DashboardController
  Action: "show"
  Security: true
  Role: "Admin"

/profile:
  Controller: Security
  Action: "profile"
  Security: true
  Role: "UserController"

/users/create:
  Controller: UserController
  Action: "add"
  Security: true
  Role: "Admin"

/users/delete:
  Controller: UserController
  Action: "delete"
  Security: true
  Role: "Admin"

/show-utilisateur:
  Controller: UserController
  Action: "show"
  Security: True
  Role: "Guest"

/users/home:
  Controller: UserController
  Action: "list"
  Security: true
  Role: "Admin"

/maj-utilisateurs:
  Controller: UserController
  Action: "edit"
  Security: true
  Role: "Guest"

/page/home:
  Controller: PageController
  Action: "list"
  Security: true
  Role: "Admin"

/page/create:
  Controller: PageController
  Action: "add"
  Security: true
  Role: "Admin"

/page/delete:
  Controller: PageController
  Action: "delete"
  Security: true
  Role: "Admin"

/show-page:
  Controller: PageController
  Action: "show"
  Security: True
  Role: "Guest"

/maj-page:
  Controller: PageController
  Action: "edit"
  Security: true
  Role: "Guest"

/article/create:
  Controller: ArticleController
  Action: "add"
  Security: true
  Role: "Admin"

/article/delete:
  Controller: ArticleController
  Action: "delete"
  Security: true
  Role: "Admin"

/show-article:
  Controller: ArticleController
  Action: "show"
  Security: True
  Role: "Guest"

/article/home:
  Controller: ArticleController
  Action: "list"
  Security: true
  Role: "Guest"

/article/edit:
  Controller: ArticleController
  Action: "edit"
  Security: true
  Role: "Admin"