/:
  Controller: "MainController"
  Action: "home"
  Security: false
  Role: "Guest"

/login:
  Controller: "Security"
  Action: "login"
  Security: false
  Role: "Guest"

/register:
  Controller: "Security"
  Action: "register"
  Security: false
  Role: "Guest"

/logout:
  Controller: "Security"
  Action: "logout"
  Security: true
  Role: "Guest"

/dashboard:
  Controller: "DashboardController"
  Action: "show"
  Security: true
  Role: "Admin"

/profile:
  Controller: "Security"
  Action: "profile"
  Security: true
  Role: "UserController"

/users/create:
  Controller: "UserController"
  Action: "add"
  Security: true
  Role: "Admin"

/del-utilisateur:
  Controller: "UserController"
  Action: "delete"
  Security: true
  Role: "Admin"

/show-utilisateur:
  Controller: "UserController"
  Action: "show"
  Security: True
  Role: "Guest"

/users/home:
  Controller: "UserController"
  Action: "list"
  Security: true
  Role: "Admin"

/maj-utilisateurs:
  Controller: "UserController"
  Action: "edit"
  Security: true
  Role: "Guest"

/page/home:
  Controller: "PageController"
  Action: "list"
  Security: true
  Role: "Admin"

/page/create:
  Controller: PageController
  Action: "add"
  Security: true
  Role: "Admin"

/del-page:
  Controller: "UserController"
  Action: "delete"
  Security: true
  Role: "Guest"

/show-page:
  Controller: "UserController"
  Action: "show"
  Security: True
  Role: "Guest"

/maj-page:
  Controller: "UserController"
  Action: "edit"
  Security: true
  Role: "Guest"

/article/create:
  Controller: "ArticleController"
  Action: "add"
  Security: true
  Role: "Admin"

/article/delete:
  Controller: "UserController"
  Action: "delete"
  Security: true
  Role: "Guest"

/show-article:
  Controller: "UserController"
  Action: "show"
  Security: True
  Role: "Guest"

/article/home:
  Controller: "ArticleController"
  Action: "list"
  Security: true
  Role: "Guest"

/maj-article:
  Controller: "UserController"
  Action: "edit"
  Security: true
  Role: "Guest"