/:
  Controller: MainController
  Action: "home"
  Security: false
  Role: "Guest"

/login:
  Controller: SecurityController
  Action: "login"
  Security: false
  Role: "Guest"

/register:
  Controller: SecurityController
  Action: "register"
  Security: false
  Role: "Guest"

/logout:
  Controller: SecurityController
  Action: "logout"
  Security: true
  Role: "User"

/accountVerification:
  Controller: SecurityController
  Action: "accountVerification"
  Security: false
  Role: "Guest"

/dashboard:
  Controller: DashboardController
  Action: "show"
  Security: true
  Role: "Editor"

/profile:
  Controller: SecurityController
  Action: "profile"
  Security: true
  Role: "User"

/users/home:
  Controller: UserController
  Action: "list"
  Security: true
  Role: "Admin"

/users/reset-password:
  Controller: SecurityController
  Action: "resetPassword"
  Security: true
  Role: "Admin"

/sendResetPassword:
  Controller: SecurityController
  Action: "sendResetPassword"
  Security: true
  Role: "User"

/resetPassword:
  Controller: SecurityController
  Action: "treatResetPassword"
  Security: false
  Role: "Guest"

/users/create:
  Controller: UserController
  Action: "add"
  Security: true
  Role: "Admin"

/users/delete:
  Controller: UserController
  Action: "delete"
  Security: true
  Role: "Admin"

/show-utilisateur:
  Controller: UserController
  Action: "show"
  Security: True
  Role: "Admin"

/users/edit:
  Controller: UserController
  Action: "edit"
  Security: true
  Role: "Admin"

/page/home:
  Controller: PageController
  Action: "list"
  Security: true
  Role: "Editor"

/page/create:
  Controller: PageController
  Action: "add"
  Security: true
  Role: "Editor"

/page/delete:
  Controller: PageController
  Action: "delete"
  Security: true
  Role: "Editor"

/show-page:
  Controller: PageController
  Action: "show"
  Security: True
  Role: ""

/page/edit:
  Controller: PageController
  Action: "edit"
  Security: true
  Role: "Editor"

/page/showPage:
  Controller: PageController
  Action: "show"
  Security: false
  Role: "Guest"

/article/create:
  Controller: ArticleController
  Action: "add"
  Security: true
  Role: "Editor"

/article/delete:
  Controller: ArticleController
  Action: "delete"
  Security: true
  Role: "Editor"

/article/home:
  Controller: ArticleController
  Action: "list"
  Security: true
  Role: "Editor"

/article/edit:
  Controller: ArticleController
  Action: "edit"
  Security: true
  Role: "Admin"

/articles:
  Controller: ArticleController
  Action: "show"
  Security: false
  Role: "Guest"

/comment/create:
  Controller: CommentController
  Action: "add"
  Security: true
  Role: "Guest"

/comment/delete:
  Controller: CommentController
  Action: "delete"
  Security: true
  Role: "Moderator"

/comments/home:
  Controller: CommentController
  Action: "list"
  Security: true
  Role: "Editor"

/comment/show:
  Controller: CommentController
  Action: "show"
  Security: True
  Role: "Editor"

/gallery:
  Controller: GalleryController
  Action: "home"
  Security: false
  Role: "Guest"

/gallery/create:
  Controller: GalleryController
  Action: "create"
  Security: true
  Role: "Editor"